services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cao-bnc-bot
    container_name: cao-bnc-bot-app-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cao-bnc-bot-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: cao-bnc-bot-nginx-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cao-bnc-bot-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: cao-bnc-bot-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cao_bnc_bot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: cao_bnc_bot
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cao-bnc-bot-network

  redis:
    image: redis:alpine
    container_name: cao-bnc-bot-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cao-bnc-bot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cao-bnc-bot-phpmyadmin-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cao-bnc-bot-network
    depends_on:
      - db

  node:
    image: node:18-alpine
    container_name: cao-bnc-bot-node-dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - cao-bnc-bot-network
    depends_on:
      - app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: cao-bnc-bot
    container_name: cao-bnc-bot-queue-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: php artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --queue=low,default
    networks:
      - cao-bnc-bot-network
    depends_on:
      - db
      - redis

volumes:
  db_data_dev:
    driver: local

networks:
  cao-bnc-bot-network:
    driver: bridge
